name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check-temporary-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for temporary git files
        run: |
          if git ls-files '*~' | grep -q '~'; then
            echo "Temporary files detected:"
            git ls-files '*~'
            exit 1
          else
            echo "No temporary files found."
          fi

      - name: Check for temporary files
        run: |
          if find . | grep '~$'; then
            echo "Temporary files detected:"
            find . | grep '~$'
            exit 1
          else
            echo "No temporary files found."
          fi

  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: blang/latex:ctanfull
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        run: latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode main.tex
        working-directory: manuscript/latex

      - name: Rename PDF
        run: |
          mv manuscript/latex/main.pdf manuscript/latex/Cnot.pdf
        
      - name: Upload PDF
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdf
          path: |
            manuscript/latex/*.pdf