name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check-temporary-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for temporary git files
        run: |
          if git ls-files '*~' | grep -q '~'; then
            echo "Temporary files detected:"
            git ls-files '*~'
            exit 1
          else
            echo "No temporary files found."
          fi

      - name: Check for temporary files
        run: |
          if find . | grep '~$'; then
            echo "Temporary files detected:"
            find . | grep '~$'
            exit 1
          else
            echo "No temporary files found."
          fi

  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Italian language package
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-lang-italian texlive-latex-extra texlive-fonts-extra texlive-extra-utils
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --reinstall -y tzdata

      - name: First build LaTeX
        run: |
          cd manuscript/latex/
          latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode main.tex

      - name: Second build LaTeX for table of contents
        run: |
          cd manuscript/latex/
          latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode main.tex

      - name: Create book version
        run: |
          cd manuscript/latex/
          pdfbook2 main.pdf

      - name: Rename PDF
        run: |
          mv manuscript/latex/main.pdf manuscript/latex/Cnot.pdf
          mv manuscript/latex/main-book.pdf manuscript/latex/Cnot_Fascicolato.pdf
        
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: |
            manuscript/latex/*.pdf