name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check-temporary-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for temporary git files
        run: |
          if git ls-files '*~' | grep -q '~'; then
            echo "Temporary files detected:"
            git ls-files '*~'
            exit 1
          else
            echo "No temporary files found."
          fi

      - name: Check for temporary files
        run: |
          if find . | grep '~$'; then
            echo "Temporary files detected:"
            find . | grep '~$'
            exit 1
          else
            echo "No temporary files found."
          fi

  build-pdf:
    container:
      image: blang/latex:ctanfull
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "manuscript/latex/main.tex"
          latexmk_use_lualatex: false
          compiler: latexmk
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Rename PDF
        run: |
          mv manuscript/latex/main.pdf manuscript/latex/Cnot.pdf
        
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: compiled-pdf
          path: |
            manuscript/latex/*.pdf